FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo
ENV DESTDIR=/install
RUN make -j8 cairo=no
RUN make install cairo=no

FROM ubuntu:20.04 as package
COPY --from=builder /repo/bin/gt /repo/bin/gt
COPY --from=builder /repo/gtdata /repo/gtdata
