#!/usr/bin/env bash
#
# genometools/mayhem/build.sh — build the `gt` tool with ASan+UBSan so Mayhem finds memory AND
# undefined-behavior defects in genometools' own code (the fuzzed target is `gt bed_to_gff3 @@`,
# a file-input target — there is no libFuzzer harness, so no $LIB_FUZZING_ENGINE / standalone here).
#
# Runs inside the commit image (mayhem/Dockerfile) as `mayhem` in /mayhem. The base image exports
# the build contract; we feed $SANITIZER_FLAGS into genometools' build via CFLAGS (the Makefile does
# EXP_CFLAGS:=$(CFLAGS), so this instruments the project itself, not just a harness).
#
# Build leanly: cairo=no (skip Cairo/Pango/X graphics deps) and useshared=no (use the bundled
# zlib/expat/lua/etc. under src/external instead of system shared libs).
set -euo pipefail

# clang rejects SOURCE_DATE_EPOCH='' (empty) — must be unset or a valid integer.
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

# Build knobs from the ENVIRONMENT (overridable), sane defaults. SANITIZER_FLAGS uses `=` (not `:=`)
# so an explicit empty value (--build-arg SANITIZER_FLAGS=) is honored → no sanitizers (natural crash).
: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer -g}"
: "${CC:=clang}" ; : "${CXX:=clang++}"
: "${MAYHEM_JOBS:=$(nproc)}"
export SANITIZER_FLAGS CC CXX MAYHEM_JOBS

cd "$SRC"

# ---------------------------------------------------------------------------------------------------
# (1) TEST-ORACLE build — a CLEAN, normal-flags `gt` for mayhem/test.sh (the C `gt -test` unit-test
# runner). The fuzz target below is sanitized + has UBSan's `function` check relaxed; an honest PATCH
# oracle must be the project's natural build, so we build `gt` with NO sanitizers and stash it at
# /mayhem/gt-test-bin. genometools has a fixed build layout (obj/, bin/, lib/) and no separate-builddir
# knob, so we build the clean `gt` FIRST, stash the binary, wipe the trees, then do the sanitized build
# into bin/gt. test.sh only RUNS this stashed binary (never compiles). Same lean knobs (cairo=no
# useshared=no) so it needs only make + the base toolchain.
echo "build.sh: building clean (no-sanitizer) gt for the test oracle (gt-test-bin)..." >&2
make -j"$MAYHEM_JOBS" cairo=no useshared=no CC="$CC"
test -x "$SRC/bin/gt" || { echo "build.sh: clean bin/gt missing after test-oracle build" >&2; exit 1; }
cp "$SRC/bin/gt" "$SRC/gt-test-bin"
# Wipe the build trees so the sanitized build is fresh (avoid `make clean`, which recurses into
# doc/ and would need extra tooling). bin/ obj/ lib/ are all regenerated by the sanitized build.
rm -rf "$SRC/bin" "$SRC/obj" "$SRC/lib"

# ---------------------------------------------------------------------------------------------------
# (2) FUZZ-TARGET build — the sanitized `bin/gt` the Mayhemfile points at.
# genometools pervasively calls through generic function pointers (void(*)(void*) destructors in
# hashmap/fa, qsort_r comparators) — a ubiquitous, benign C idiom that UBSan's `function` check flags.
# With the default -fno-sanitize-recover it aborts in `gt`'s init on EVERY input (even `gt -help`),
# so the target can't fuzz at all. Relax ONLY that one check (ASan + the rest of UBSan stay on and
# halting) when UBSan is in play; the empty off-switch (SANITIZER_FLAGS=) stays untouched.
FLAGS="$SANITIZER_FLAGS"
case "$SANITIZER_FLAGS" in *undefined*) FLAGS="$SANITIZER_FLAGS -fno-sanitize=function" ;; esac

# Build genometools (and `bin/gt`) with the sanitizers instrumented into the project.
# genometools threads CFLAGS into EXP_CFLAGS, so $FLAGS instruments its own code.
# -Wno-error guard: errorcheck is off by default, so warnings from instrumentation won't fail the build.
make -j"$MAYHEM_JOBS" cairo=no useshared=no \
     CC="$CC" CFLAGS="$FLAGS" \
     LDFLAGS="$FLAGS"

# Sanity: the fuzz target binary must exist where the Mayhemfile points (/mayhem/bin/gt).
test -x "$SRC/bin/gt" || { echo "build.sh: bin/gt missing after build" >&2; exit 1; }
test -x "$SRC/gt-test-bin" || { echo "build.sh: gt-test-bin missing (test oracle)" >&2; exit 1; }
